-- Autonomous Supply Chain Workflow System
-- Migration for comprehensive workflow orchestration

-- Supply chain workflow definitions
CREATE TABLE IF NOT EXISTS `supplyChainWorkflows` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `companyId` int,
  `name` varchar(255) NOT NULL,
  `description` text,
  `workflowType` enum('demand_forecasting','production_planning','material_requirements','procurement','inventory_reorder','inventory_transfer','inventory_optimization','work_order_generation','production_scheduling','freight_procurement','shipment_tracking','order_fulfillment','supplier_management','quality_inspection','invoice_matching','payment_processing','exception_handling','custom') NOT NULL,
  `triggerType` enum('scheduled','event','threshold','manual','continuous') NOT NULL DEFAULT 'scheduled',
  `cronSchedule` varchar(64),
  `triggerEvents` text,
  `thresholdConfig` text,
  `executionConfig` text,
  `maxConcurrentRuns` int DEFAULT 1,
  `timeoutMinutes` int DEFAULT 60,
  `retryAttempts` int DEFAULT 3,
  `retryDelayMinutes` int DEFAULT 5,
  `requiresApproval` boolean NOT NULL DEFAULT false,
  `autoApproveThreshold` decimal(14,2),
  `approvalRoles` text,
  `escalationMinutes` int DEFAULT 60,
  `escalationRoles` text,
  `dependsOnWorkflows` text,
  `isActive` boolean NOT NULL DEFAULT true,
  `lastRunAt` timestamp,
  `nextScheduledRun` timestamp,
  `successCount` int DEFAULT 0,
  `failureCount` int DEFAULT 0,
  `createdBy` int,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Workflow execution runs
CREATE TABLE IF NOT EXISTS `workflowRuns` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `workflowId` int NOT NULL,
  `runNumber` varchar(64) NOT NULL,
  `status` enum('queued','running','awaiting_approval','approved','rejected','completed','failed','cancelled','timed_out') NOT NULL DEFAULT 'queued',
  `triggeredBy` enum('schedule','event','threshold','manual','dependency') NOT NULL,
  `triggerData` text,
  `triggeredByUserId` int,
  `startedAt` timestamp,
  `completedAt` timestamp,
  `durationMs` int,
  `totalSteps` int DEFAULT 0,
  `completedSteps` int DEFAULT 0,
  `currentStepName` varchar(255),
  `progressPercent` int DEFAULT 0,
  `inputData` text,
  `outputData` text,
  `errorMessage` text,
  `errorDetails` text,
  `itemsProcessed` int DEFAULT 0,
  `itemsSucceeded` int DEFAULT 0,
  `itemsFailed` int DEFAULT 0,
  `totalValue` decimal(14,2),
  `attemptNumber` int DEFAULT 1,
  `parentRunId` int,
  `approvalRequestedAt` timestamp,
  `approvedBy` int,
  `approvedAt` timestamp,
  `rejectedBy` int,
  `rejectedAt` timestamp,
  `rejectionReason` text,
  `escalatedAt` timestamp,
  `escalatedTo` text,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_workflow_runs_workflow` (`workflowId`),
  INDEX `idx_workflow_runs_status` (`status`),
  INDEX `idx_workflow_runs_created` (`createdAt`)
);

-- Workflow steps
CREATE TABLE IF NOT EXISTS `workflowSteps` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `runId` int NOT NULL,
  `stepNumber` int NOT NULL,
  `stepName` varchar(255) NOT NULL,
  `stepType` enum('data_fetch','ai_analysis','ai_decision','calculation','validation','create_record','update_record','send_email','send_notification','api_call','wait_approval','condition_check','loop_start','loop_end','parallel_start','parallel_end','subprocess') NOT NULL,
  `status` enum('pending','running','completed','failed','skipped','awaiting_input') NOT NULL DEFAULT 'pending',
  `startedAt` timestamp,
  `completedAt` timestamp,
  `durationMs` int,
  `inputData` text,
  `outputData` text,
  `errorMessage` text,
  `aiPrompt` text,
  `aiResponse` text,
  `aiConfidence` decimal(5,2),
  `aiTokensUsed` int,
  `createdEntityType` varchar(64),
  `createdEntityId` int,
  `modifiedEntityType` varchar(64),
  `modifiedEntityId` int,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_workflow_steps_run` (`runId`)
);

-- Workflow approval queue
CREATE TABLE IF NOT EXISTS `workflowApprovalQueue` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `runId` int NOT NULL,
  `approvalType` enum('purchase_order','work_order','inventory_transfer','freight_booking','payment','price_change','vendor_selection','exception_override','forecast_adjustment','workflow_result') NOT NULL,
  `title` varchar(500) NOT NULL,
  `description` text,
  `monetaryValue` decimal(14,2),
  `currency` varchar(3) DEFAULT 'USD',
  `contextData` text,
  `aiRecommendation` text,
  `aiConfidence` decimal(5,2),
  `riskAssessment` enum('low','medium','high','critical') DEFAULT 'low',
  `relatedEntityType` varchar(64),
  `relatedEntityId` int,
  `status` enum('pending','approved','rejected','auto_approved','escalated','expired') NOT NULL DEFAULT 'pending',
  `assignedToRoles` text,
  `assignedToUsers` text,
  `currentAssignee` int,
  `requestedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dueAt` timestamp,
  `escalateAt` timestamp,
  `escalatedAt` timestamp,
  `escalationLevel` int DEFAULT 0,
  `resolvedBy` int,
  `resolvedAt` timestamp,
  `resolutionNotes` text,
  `wasAutoApproved` boolean DEFAULT false,
  `autoApprovalReason` varchar(255),
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_approval_queue_status` (`status`),
  INDEX `idx_approval_queue_run` (`runId`)
);

-- Autonomous decisions log
CREATE TABLE IF NOT EXISTS `autonomousDecisions` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `runId` int,
  `stepId` int,
  `decisionType` enum('vendor_selection','quantity_calculation','timing_decision','routing_decision','pricing_acceptance','exception_handling','priority_assignment','allocation_decision','forecast_adjustment','reorder_trigger','approval_routing') NOT NULL,
  `decisionContext` text,
  `optionsConsidered` text,
  `chosenOption` text,
  `aiReasoning` text,
  `confidence` decimal(5,2),
  `entityType` varchar(64),
  `entityId` int,
  `estimatedImpact` text,
  `actualImpact` text,
  `wasOverridden` boolean DEFAULT false,
  `overriddenBy` int,
  `overrideReason` text,
  `feedbackScore` int,
  `feedbackNotes` text,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_decisions_run` (`runId`),
  INDEX `idx_decisions_type` (`decisionType`)
);

-- Supply chain events
CREATE TABLE IF NOT EXISTS `supplyChainEvents` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `eventType` enum('inventory_low','inventory_critical','inventory_excess','inventory_expiring','inventory_received','inventory_adjustment','order_created','order_confirmed','order_shipped','order_delivered','order_cancelled','po_created','po_sent','po_confirmed','po_shipped','po_received','po_discrepancy','work_order_created','production_started','production_completed','production_issue','yield_variance','quote_received','price_change','lead_time_change','supplier_issue','shipment_booked','shipment_picked_up','shipment_delayed','shipment_delivered','customs_hold','quality_issue','inspection_failed','inspection_passed','invoice_received','payment_due','payment_overdue','forecast_generated','demand_spike','demand_drop','workflow_completed','workflow_failed','approval_needed','escalation_triggered') NOT NULL,
  `severity` enum('info','warning','error','critical') NOT NULL DEFAULT 'info',
  `sourceSystem` varchar(64),
  `sourceEntityType` varchar(64),
  `sourceEntityId` int,
  `eventData` text,
  `summary` varchar(500),
  `isProcessed` boolean DEFAULT false,
  `processedAt` timestamp,
  `processedByWorkflowId` int,
  `processedByRunId` int,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_events_type` (`eventType`),
  INDEX `idx_events_processed` (`isProcessed`),
  INDEX `idx_events_created` (`createdAt`)
);

-- Workflow metrics
CREATE TABLE IF NOT EXISTS `workflowMetrics` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `workflowId` int NOT NULL,
  `metricDate` timestamp NOT NULL,
  `totalRuns` int DEFAULT 0,
  `successfulRuns` int DEFAULT 0,
  `failedRuns` int DEFAULT 0,
  `averageDurationMs` int,
  `maxDurationMs` int,
  `autoApprovedCount` int DEFAULT 0,
  `manualApprovedCount` int DEFAULT 0,
  `rejectedCount` int DEFAULT 0,
  `averageApprovalTimeMs` int,
  `escalationCount` int DEFAULT 0,
  `itemsProcessed` int DEFAULT 0,
  `totalValueProcessed` decimal(18,2),
  `exceptionsHandled` int DEFAULT 0,
  `aiDecisionCount` int DEFAULT 0,
  `aiOverrideCount` int DEFAULT 0,
  `averageAiConfidence` decimal(5,2),
  `totalTokensUsed` int DEFAULT 0,
  `estimatedTimeSavedMinutes` int,
  `estimatedCostSavings` decimal(14,2),
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_metrics_workflow` (`workflowId`),
  INDEX `idx_metrics_date` (`metricDate`)
);

-- Approval thresholds
CREATE TABLE IF NOT EXISTS `approvalThresholds` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `companyId` int,
  `name` varchar(255) NOT NULL,
  `entityType` enum('purchase_order','work_order','inventory_transfer','freight_booking','payment','vendor_rfq','price_override','exception') NOT NULL,
  `autoApproveMaxAmount` decimal(14,2),
  `level1MaxAmount` decimal(14,2),
  `level2MaxAmount` decimal(14,2),
  `level3MaxAmount` decimal(14,2),
  `level1Roles` text,
  `level2Roles` text,
  `level3Roles` text,
  `execRoles` text,
  `level1EscalationMinutes` int DEFAULT 60,
  `level2EscalationMinutes` int DEFAULT 120,
  `level3EscalationMinutes` int DEFAULT 240,
  `conditions` text,
  `isActive` boolean NOT NULL DEFAULT true,
  `createdBy` int,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Exception handling rules
CREATE TABLE IF NOT EXISTS `exceptionRules` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `companyId` int,
  `name` varchar(255) NOT NULL,
  `description` text,
  `exceptionType` enum('quantity_mismatch','price_variance','quality_issue','delivery_delay','stockout','overstock','supplier_unavailable','capacity_constraint','forecast_deviation','payment_issue','documentation_missing','customs_issue','other') NOT NULL,
  `matchConditions` text,
  `varianceThresholdPercent` decimal(5,2),
  `resolutionStrategy` enum('auto_resolve','ai_decide','route_to_human','escalate','apply_default','notify_and_continue','halt_workflow') NOT NULL,
  `autoResolutionAction` text,
  `defaultAction` text,
  `notifyRoles` text,
  `assignToRole` varchar(64),
  `resolveWithinMinutes` int DEFAULT 60,
  `escalateAfterMinutes` int DEFAULT 120,
  `priority` int DEFAULT 100,
  `isActive` boolean NOT NULL DEFAULT true,
  `createdBy` int,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Exception log
CREATE TABLE IF NOT EXISTS `exceptionLog` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `runId` int,
  `stepId` int,
  `ruleId` int,
  `exceptionType` varchar(64) NOT NULL,
  `severity` enum('low','medium','high','critical') NOT NULL DEFAULT 'medium',
  `title` varchar(500) NOT NULL,
  `description` text,
  `exceptionData` text,
  `entityType` varchar(64),
  `entityId` int,
  `status` enum('open','in_progress','resolved','escalated','ignored') NOT NULL DEFAULT 'open',
  `resolutionType` enum('auto_resolved','ai_resolved','human_resolved','escalated_resolved','ignored'),
  `resolutionAction` text,
  `resolutionNotes` text,
  `resolvedBy` int,
  `resolvedAt` timestamp,
  `financialImpact` decimal(14,2),
  `operationalImpact` varchar(255),
  `detectedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dueAt` timestamp,
  `escalatedAt` timestamp,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_exception_status` (`status`),
  INDEX `idx_exception_severity` (`severity`)
);

-- Supplier performance scores
CREATE TABLE IF NOT EXISTS `supplierPerformance` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `vendorId` int NOT NULL,
  `metricMonth` varchar(7) NOT NULL,
  `totalOrders` int DEFAULT 0,
  `onTimeDeliveries` int DEFAULT 0,
  `lateDeliveries` int DEFAULT 0,
  `averageLeadTimeDays` decimal(8,2),
  `leadTimeVarianceDays` decimal(8,2),
  `totalItemsReceived` int DEFAULT 0,
  `qualityPassCount` int DEFAULT 0,
  `qualityFailCount` int DEFAULT 0,
  `qualityPassRate` decimal(5,2),
  `quantityMatchCount` int DEFAULT 0,
  `quantityVarianceCount` int DEFAULT 0,
  `totalSpend` decimal(18,2),
  `averagePriceVariancePercent` decimal(6,2),
  `averageResponseTimeHours` decimal(8,2),
  `issuesReported` int DEFAULT 0,
  `issuesResolved` int DEFAULT 0,
  `deliveryScore` decimal(5,2),
  `qualityScore` decimal(5,2),
  `priceScore` decimal(5,2),
  `responsiveScore` decimal(5,2),
  `overallScore` decimal(5,2),
  `aiAssessment` text,
  `recommendedActions` text,
  `riskLevel` enum('low','medium','high') DEFAULT 'low',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_supplier_perf_vendor` (`vendorId`),
  INDEX `idx_supplier_perf_month` (`metricMonth`)
);

-- Workflow notifications
CREATE TABLE IF NOT EXISTS `workflowNotifications` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `runId` int,
  `notificationType` enum('info','warning','error','approval_needed','approval_completed','exception','milestone','completion') NOT NULL,
  `title` varchar(500) NOT NULL,
  `message` text,
  `targetRoles` text,
  `targetUserIds` text,
  `sendEmail` boolean DEFAULT false,
  `sendInApp` boolean DEFAULT true,
  `sendSlack` boolean DEFAULT false,
  `isRead` boolean DEFAULT false,
  `readBy` int,
  `readAt` timestamp,
  `actionUrl` varchar(500),
  `actionLabel` varchar(100),
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_notifications_run` (`runId`),
  INDEX `idx_notifications_read` (`isRead`)
);
